spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
#                url: jdbc:mysql://172.16.104.27:3306/operating_unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#                url: jdbc:mysql://127.0.0.1:3306/operating_unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
                url: jdbc:mysql://132.115.207.101:3307/operating_unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
                username: root
#                password: 123456
                password: I/QqOJI4G8ZA
            second:  #数据源2
#                url: jdbc:mysql://localhost:3306/shiro_jwt1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
                url: jdbc:mysql://132.115.207.101:3307/operating_unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
                username: root
#                password: 123456
#                password: I/QqOJI4G8ZA
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    678-sql: true
                wall:
                    config:
                        multi-statement-allow: true
file:
    # 文件上传目录
    uploadFolder: /usr/local/upload
    # 对外访问的资源路径
    staticAccessPath: /uploadfile/**