server:
  port: 9099
  tomcat:
    max-http-post-size: -1
    uri-encoding: utf-8
  max-http-header-size: 4048576
  servlet:
    context-path: /operating_unit

# mysql
spring:
   # 环境 dev|aspect|pro
   profiles:
       active: local
   # jackson时间格式化
   jackson:
       time-zone: GMT+8
       date-format: yyyy-MM-dd HH:mm:ss
   redis:
       database: 0
       host: 127.0.0.1
       port: 6379
       timeout: 2000
   servlet:
     multipart:
       # 设置文件上传大小
       max-file-size: 1000MB
       max-request-size: 1000MB


mybatis-plus:
  #映射路径
  mapper-locations: classpath:/mapper/**/*.xml
  #sql对应的实体
  type-aliases-package: com.gpdi.operatingunit.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: cn.jeefast.xxx
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#热部署配置
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
    additional-exclude: views/**